#!/bin/bash

echo '-----------------------------------------------------------'
echo '---------- FreeEMS - Developers install script ------------'
echo '-----------------------------------------------------------'
echo ' FreeEMS - the open source engine management system		  ' 
echo 
echo ' Copyright 2012 Preston Saunders '
echo  
echo ' This file is part of the FreeEMS project. '
echo  
echo ' Thank you for choosing FreeEMS to run your engine! '
echo '-----------------------------------------------------------'
echo
echo 'This install script is intended for use on fresh installs of'
echo 'Debian, it will download, install and configure the 		   '
echo 'necessary tools; USE AT YOUR OWN RISK!							   '
echo
echo '==========================================================='
echo '--- This install requires an active internet connection ---'
echo '==========================================================='
echo
echo '       *** hit ctrl c to cancel at any stage *** '
echo

sleep 3

#TODO have to options for 'FreeEMS users' install and a 'developers' install.
echo 'Do you want to continue [Y/n]?'; read scriptRun
if [ "$scriptRun" == "Y" -o "$scriptRun" == "y" -o "$scriptRun" == "" ]; then

echo 'Please type your login user name, and press enter' ; read user

# Make FreeEMS directorys.
mkdir ~/workspaces/freeems

# create symlink on desktop if desktop exsits
if [ -d "$Desktop" ]; then
   cd ~/Desktop
	ln -s ~/workspaces/ workspaces
fi

#Add Dialout to standard user groups and refresh database
sudo adduser $user dialout
updatedb

# Update application cache
sudo apt-get update

# Install git
sudo apt-get install git-core

# Clone repository's
cd ~/workspaces/freeems/				
git clone git://github.com/FreeEMS/freeems-vanilla.git	
git clone git://github.com/FreeEMS/OpenLogViewer.git				
git clone git://github.com/FreeEMS/freeems-loader.git

#check for quick start dir and create if it does not exist
if [ -d "$FreeEMS-Quick-Start" ]; then
	git pull git://github.com/FreeEMS/FreeEMS-Quick-Start.git			
else
	git clone git://github.com/FreeEMS/FreeEMS-Quick-Start.git
fi

mkdir ~/bin
#add scripts to bin dir
#TODO
 
#maven install make dirs maven and maven3 
mkdir /usr/local/maven 
#TODO maven and OLV install

#Mega-Tunix clone and install
git clone git://github.com/FreeEMS/MegaTunix.git	 		
cd ~/workspaces/freeems/MegaTunix/ 						
sudo apt-get install autoconf libtool intltool flex bison libpango1.0-dev libglade2-dev libgtkglext1-dev g++
sudo ./autogen.sh						
make
sudo make install
sudo ldconfig

echo '
export PATH=$PATH:~/bin' >> ~/.bashrc				#yes the blankness is meant to be on the above line.
echo 'export PATH=$PATH:~/Desktop/workspaces/freeems/freeems-vanilla/bin/' >> ~/.bashrc
echo 'export PATH=$PATH:~/usr/local/maven/bin' >> ~/.bashrc

#Install additional apps
echo 'Would you like to install Cutecom [Y/n]?'; read cutecomInstall
if [ "$cutecomInstall" == "Y" -o "$cutecomInstall" == "y" -o "$cutecomInstall" == "" ] ; then
	sudo apt-get -y install cutecom					#install of serial communications application
else 
echo "Cutecom install skipped"
fi

echo 'Would you like to install kdiff3 [Y/n]?'; read kdiff3Install
if [ "$kdiff3Install" == "Y" -o "$kdiff3Install" == "y" -o "$kdiff3Install" == "" ] ; then
	sudo apt-get -y install kdiff3					#install of file diffing application
else 
echo "Kdiff3 install skipped"
fi

echo
echo '** Install Complete **'
echo 
echo 'TODO add how to use what has been installed'
exit 0;

else
echo
echo 'script ABORTED'
exit 0;
fi