#!/bin/bash

clear;

echo '-----------------------------------------------------------'
echo '---------- FreeEMS - Developers install script ------------'
echo '-----------------------------------------------------------'
echo ' FreeEMS - the open source engine management system		  ' 
echo 
echo ' Copyright 2012 Preston Saunders '
echo  
echo ' This file is part of the FreeEMS project. '
echo  
echo ' Thank you for choosing FreeEMS to run your engine! '
echo '-----------------------------------------------------------'
echo
echo 'This install script is intended for use on fresh installs of'
echo 'Debian, it will download, install and configure the 		  '
echo 'necessary tools; USE AT YOUR OWN RISK!							  '
echo
echo '==========================================================='
echo '--- This install requires an active internet connection ---'
echo '==========================================================='
echo
echo '       *** hit ctrl c to cancel at any stage *** '
echo

sleep 3

#TODO have to options for 'FreeEMS users' install and a 'developers' install.
echo 'Do you want to continue [Y/n]?'; read scriptRun
if [ "$scriptRun" == "Y" -o "$scriptRun" == "y" -o "$scriptRun" == "" ]; then

# Make FreeEMS, home and user bin directorys.
mkdir ~/Desktop/workspaces 
mkdir ~/Desktop/workspaces/freeems
mkdir ~/bin 

# Update application cache
sudo apt-get update

# Install git
sudo apt-get install git

# Clone repository's
cd ~/Desktop/workspaces/freeems/				
git clone git://github.com/FreeEMS/freeems-vanilla.git	
git clone git://github.com/FreeEMS/OpenLogViewer.git				
git clone git://github.com/FreeEMS/freeems-loader.git			
#git clone git://github.com/presto/freeems-log-reports.git	
#git clone git://github.com/presto/freeems-scripts.git		
#git pull git://github.com/FreeEMS/FreeEMS-Quick-Start.git

#maven install make dirs maven and maven3 
mkdir /usr/local/maven 
mkdir /usr/local/maven3 
#TODO maven and OLV install

#Mega-Tunix clone and install
git clone git://github.com/FreeEMS/MegaTunix.git	 		
cd ~/Desktop/workspaces/freeems/MegaTunix/ 						
sudo apt-get install autoconf libtool intltool flex bison libpango1.0-dev libglade2-dev libgtkglext1-dev g++
sudo ./autogen.sh						
make
sudo make install
sudo ldconfig

#Install additional apps
echo 'Would you like to install Cutecom [Y/n]?'; read cutecomInstall
if [ "$cutecomInstall" == "Y" -o "$cutecomInstall" == "y" -o "$cutecomInstall" == "" ] ; then
	sudo apt-get -y install cutecom					#install of serial communications application
else 
echo "Cutecom install skipped"
fi

echo 'Would you like to install kdiff3 [Y/n]?'; read kdiff3Install
if [ "$kdiff3Install" == "Y" -o "$kdiff3Install" == "y" -o "$kdiff3Install" == "" ] ; then
	sudo apt-get -y install kdiff3					#install of file diffing application
else 
echo "Kdiff3 install skipped"
fi

# Add the following entries to .bashrc
cp ~/.bashrc ~/.bashrc.backup 					#save a copy of .bashrc before modification to ~/ dir
echo '
export PATH=$PATH:~/bin' >> ~/.bashrc				#yes the blankness is meant to be on the above line.
echo 'export PATH=$PATH:~/Desktop/workspaces/freeems/freeems-vanilla/bin/' >> ~/.bashrc
echo 'export PATH=$PATH:~/usr/local/maven/bin' >> ~/.bashrc

#TODO add 'olv' script to bin for open log viewer universal run
#TODO add 'FreeEMS-Loader' script to bin for universal run
#TODO copy scripts to ~/bin dir
#TODO create a log file

echo
echo '** Install Complete **'
echo 
echo 'TODO add How to use what has been installed'
exit 0;

else
echo
echo 'script ABORTED'
echo
exit 0;
fi